### PR TITLE
Update ListTransform.swift

### PR DESCRIPTION
**Pull request by akovalov**
Swift 3 support

### CODE REVIEW

**Comment by levibostian** [comment]
Just tried this in my app using Swift 3 with no issues. 

Since this is not in the main repo, I simply copied the pull request file into my project manually.

**Comment by hanief** [comment]
I have tried this and it works. Thank you for saving me from the troubles.

**Comment by codytwinton** [comment]
@hanief - Can you push this change to Cocoapods?

**Comment by codytwinton** [comment]
@hanief - Can you issue a new release for this update, so that this code change can be reflected in the Cocoapods version?

**Comment by hanief** [comment]
@codytwinton i am not the repo owner, maybe @Jakenberg can help you?

**Comment by codytwinton** [comment]
@hanief @Jakenberg - The new release is out, but still not live on the Cocoapods repo. Can you push the pod update with `pod trunk`? The [Cocoapod](http://cocoapods.org/pods/ObjectMapper+Realm) still shows the latest release being in August.

**Pull request merged**
